<?php

namespace CrCms\Foundation\Swoole\Events;
use Swoole\Async;
use Swoole\Server;

/**
 * Class ReceiveEvent
 * @package CrCms\Foundation\Swoole\Events
 */
class ReceiveEvent extends AbstractEvent implements EventContract
{
    protected $fd;

    protected $formId;

    protected $data;

    public function __construct(int $fd, int $fromId, string $data)
    {
        $this->fd = $fd;
        $this->formId = $fromId;
        $this->data = $data;
    }

    public function handle(Server $server) : void
    {
        parent::handle($server); // TODO: Change the autogenerated stub
    }

}