<?php

namespace CrCms\Foundation\Swoole\Events;


use Swoole\Server;

class StartEvent extends AbstractEvent implements EventContract
{


    public function handle(Server $server): void
    {
        parent::handle($server); // TODO: Change the autogenerated stub

        cli_set_process_title('reload_master');
    }

}