<?php
/**
 * Created by PhpStorm.
 * User: simon
 * Date: 2016/10/21
 * Time: 17:11
 */

namespace Simon\User\Repositories;


use Simon\Kernel\Repositories\AbstractRepository;
use Simon\User\Models\Secret;
use Simon\User\Repositories\Interfaces\SecretRepositoryInterface;

class SecretRepository extends AbstractRepository implements SecretRepositoryInterface
{

    /**
     * SecretRepository constructor.
     * @param Secret $model
     */
    public function __construct(Secret $model)
    {
        parent::__construct($model);
    }


    /**
     * @param array $data
     * @return Secret
     */
    public function create(array $data) : Secret
    {
        // TODO: Change the autogenerated stub

        $secretKey = str_random(10);

        return parent::create([
            'secret_key'=>$secretKey
        ]);
    }
}