<?php
/**
 * Created by PhpStorm.
 * User: simon
 * Date: 2016/8/20
 * Time: 20:01
 */
namespace Simon\Kernel\Providers;
use Simon\Kernel\Providers\PackageServiceProvider;
use Illuminate\Support\ServiceProvider;
use Simon\Kernel\Services\Interfaces\VisitedInterface;
use Simon\Kernel\Services\Visited;


class KernelServiceProvider extends PackageServiceProvider
{

    protected $defer = false;

    /**
     *
     * @var string
     * @author simon
     */
    protected $namespaceName = 'kernel';

    /**
     *
     * @var string
     * @author simon
     */
    protected $packagePath = __DIR__.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR;


    public function register()
    {
        // TODO: Change the autogenerated stub
        parent::register();

        $this->app->singleton([VisitedInterface::class=>'visited'],function($app){
           return new Visited($app['request']->ip(),$app['cache']->store());
        });
    }

    /**
     *
     */

    /**
     * Get the services provided by the provider.
     *
     * @return array
     */
    public function provides()
    {
//        return [];
    }



}