<?php
/**
 * Created by PhpStorm.
 * User: simon
 * Date: 2016/9/18
 * Time: 18:29
 */

namespace Simon\Discuss\Repositorys;


use Simon\Discuss\Models\Discuss;
use Simon\Discuss\Models\DiscussData;
use Simon\Discuss\Repositorys\Interfaces\DiscussRepositoryInterface;
use Simon\Kernel\Repositorys\AbstraceRepository;

class DiscussRepository extends AbstraceRepository implements DiscussRepositoryInterface
{

    const STATUS_OPEN = 1;

    const STATUS_CLOSE = 2;

    protected $discussDataModel = null;

    public function __construct(Discuss $Model,DiscussData $discussData)
    {
        parent::__construct($Model);

        $this->discussDataModel = $discussData;
    }

    public function create(array $data)
    {
        // TODO: Change the autogenerated stub
        $model = parent::create([
            'title'=>$data['title'],
            'status'=>static::STATUS_OPEN,
        ]);

        $this->discussDataModel->create([
            'did'=>$model->id,
            'content'=>$data['content'],
        ]);

        return $model;
    }

}