<?php

namespace CrCms\Foundation\Swoole\Events\WebSocket;

use CrCms\Foundation\Swoole\Events\AbstractEvent;
use CrCms\Foundation\Swoole\Events\EventContract;
use Swoole\Http\Request;
use Swoole\Http\Response;
use Swoole\Server;
use Swoole\WebSocket\Frame;

/**
 * Class MessageEvent
 * @package CrCms\Foundation\Swoole\Events
 */
class MessageEvent extends AbstractEvent implements EventContract
{
    protected $frame;

    public function __construct(Frame $frame)
    {
        $this->frame = $frame;
    }

    public function handle(Server $server) : void
    {
        parent::handle($server); // TODO: Change the autogenerated stub

        dump($this->server->open->getRequest());
//        $this->server->on('request',[$this,'onRequest']);
        $this->server->push($this->frame->fd, "this is server");
        var_dump($this->frame->data);
        //$server->on('abc')
    }

    public function onRequest(Request $request,Response $response)
    {
        dump(123);
        dump($request->server['request_uri']);
    }
}