<?php

namespace CrCms\Foundation\Swoole\Events\WebSocket;
use CrCms\Foundation\Swoole\Events\AbstractEvent;
use CrCms\Foundation\Swoole\Events\EventContract;
use Swoole\Http\Request;
use Swoole\Server;

/**
 * Class OpenEvent
 * @package CrCms\Foundation\Swoole\Events
 */
class OpenEvent extends AbstractEvent implements EventContract
{
    protected $request;

    public function __construct(Request $request)
    {
        $this->request = $request;
    }

    public function handle(Server $server) : void
    {
        parent::handle($server); // TODO: Change the autogenerated stub


    }

    public function getRequest(): Request
    {
        return $this->request;
    }


}