<?php
/**
 * Created by PhpStorm.
 * User: simon
 * Date: 2016/9/1
 * Time: 11:18
 */

namespace Simon\Acl\Repositorys;


use Simon\Acl\Models\Permission;
use Simon\Acl\Repositorys\Interfaces\PermissionRepositoryInterface;
use Simon\Kernel\Repositorys\AbstraceRepository;

class PermissionRepository extends AbstraceRepository implements PermissionRepositoryInterface
{

    const STATUS_OPEN = 1;

    const STATUS_CLOSE = 2;

    const STATUS = [self::STATUS_OPEN=>'开启',self::STATUS_CLOSE=>'关闭'];

    public function __construct(Permission $Model)
    {
        parent::__construct($Model);
    }

    /**
     * @param array $data
     * @return static
     */
    public function create(array $data)
    {
        // TODO: Change the autogenerated stub
        return parent::create([
            'node'=>strtoupper($data['node']),
            'app_id'=>$data['app_id'],
            'remark'=>$data['remark'],
            'name'=>$data['name'],
            'status'=>$data['status'],
        ]);
    }


    public function update(array $data, int $id)
    {
        // TODO: Change the autogenerated stub

        return parent::update([
//            'node'=>$data['node'],
//            'app_id'=>$data['app_id'],
            'remark'=>$data['remark'],
            'name'=>$data['name'],
            'status'=>$data['status'],
        ], $id);
    }

    public function status() : array
    {
        return static::STATUS;
    }

    public function statusOpen() : int
    {
        return static::STATUS_OPEN;
    }

    public function statusClose() : int
    {
        return static::STATUS_CLOSE;
    }

}